name: lhmm-dev

services:
  server:
    container_name: lhmm-backend
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    working_dir: /lhmm/app/backend
    command: uvicorn lhmm.main:app --reload --host 0.0.0.0 --port 8080
    environment:
      TZ: America/Los_Angeles
      LHMM_ROOT: /lhmm
      LHMM_APP_DIR: /lhmm/app
      LHMM_BACKEND_DIR: /lhmm/app/backend
      LHMM_FRONTEND_DIR: /lhmm/app/frontend
      LHMM_CONFIG_DIR: /lhmm/config
      LHMM_LOG_DIR: /lhmm/logs
      LHMM_MEDIA_ROOT: /lhmm/media
      LHMM_DB_URL: sqlite:////lhmm/config/db/lhmm.sqlite3
      LHMM__TMDB__API_KEY: ${TMDB_API_KEY}
      LHMM__CORS__ALLOWED_ORIGINS: ${LHMM__CORS__ALLOWED_ORIGINS}
    volumes:
      - ./server:/lhmm/app/backend
      - ./web:/lhmm/app/frontend
      - /Volumes/kdev/lhmm-demo/config:/lhmm/config
      - /Volumes/kdev/lhmm-demo/logs:/lhmm/logs
      - /Volumes/media:/lhmm/media
    networks: [lhmmnet]

  web:
    container_name: lhmm-frontend
    image: node:20
    user: "1000:1000"
    working_dir: /lhmm/app/frontend
    command: sh -lc 'if [ -f package-lock.json ]; then npm ci; else npm install; fi && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort'
    environment:
      - CHOKIDAR_USEPOLLING=1
      - DEV_DOMAIN=${DEV_DOMAIN}
    volumes:
      - ./web:/lhmm/app/frontend
    depends_on: [server]
    networks: [lhmmnet]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: lhmm-cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - server
      - web
    networks: [lhmmnet]
  
networks:
  lhmmnet:
    driver: bridge

