name: "Feature request (short)"
description: "Quick feature idea for Lighthouse"
title: "feat: "
labels: ["feature"]
assignees: []

body:
  - type: textarea
    id: what
    attributes:
      label: What feature would you like to see added?
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful to you?
      placeholder: Why is this useful to you?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Urgent
    validations:
      required: true

  - type: textarea
    id: extras
    attributes:
      label: Anything else? (optional)
      placeholder: Links or screenshots (drag & drop works)