"""init schema

Revision ID: 4b2a803e95b3
Revises: 
Create Date: 2025-08-14 20:50:29.688429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2a803e95b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('mount_path', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indexers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=True),
    sa.Column('capabilities_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(length=512), nullable=True),
    sa.Column('backdrop_path', sa.String(length=512), nullable=True),
    sa.Column('added_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'tmdb_id', name='uq_mediaitem_kind_tmdb')
    )
    op.create_index('ix_mediaitem_title', 'media_items', ['title'], unique=False)
    op.create_index('ix_mediaitem_tmdb', 'media_items', ['tmdb_id'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('root_disk_id', sa.Integer(), nullable=False),
    sa.Column('root_subdir', sa.String(length=256), nullable=False),
    sa.Column('settings_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['root_disk_id'], ['disks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_libraries_type', 'libraries', ['type'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('quality_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'rel_path', name='uq_file_unique_per_library')
    )
    op.create_index('ix_mediafile_item', 'media_files', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mediafile_item', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index('ix_libraries_type', table_name='libraries')
    op.drop_table('libraries')
    op.drop_index('ix_mediaitem_tmdb', table_name='media_items')
    op.drop_index('ix_mediaitem_title', table_name='media_items')
    op.drop_table('media_items')
    op.drop_table('jobs')
    op.drop_table('indexers')
    op.drop_table('disks')
    # ### end Alembic commands ###
